#' getCDEC - a function generated by getXML::createFunction
#'
#' @param sensor_num The number of the sensor you want (for a full list of sensors, see: )
#' @param start_date The start date of the data, in mm/dd/yyyy format
#' @param end_date The end date of the data you want, in mm/dd/yyyy format
#' @param station_id The three letter station ID, quoted and in all caps (for a full list of station ids, see: )
#' @param dur_code The code of the data duration you want.
#' @details  dates must be in mm/dd/yyyy format, type of data and station is quoted, sensor number is numeric.
# "05/01/2011", 20, "03/01/2011", "E", "FPT"
#' @return The data between the specified \code{start_date} and \code{end_date}, in table format
#' @export
#' @examples
#' d <- getCDEC(20, "03/01/2011", "05/01/2011", "FPT", "E")
#' head(d)

f2 = RHTMLForms::getHTMLFormDescription("http://cdec.water.ca.gov/cgi-progs/queryCSV")
fun2 = RHTMLForms::createFunction(f2[[4]], reader = function(x) read.csv(textConnection(x), stringsAsFactors = FALSE, skip = 1))

# Change the order of the parameters
f2[[4]]$elements = f2[[4]]$elements[c(5, 3, 4, 2, 1)]

getCDEC = RHTMLForms::createFunction(f2[[4]], reader = function(x) read.csv(textConnection(x), stringsAsFactors = FALSE, skip = 1))
